#!/usr/bin/env python

import os, sys, string, re, cPickle, subprocess

if len(sys.argv) > 2:
    root = sys.argv[2]
else:
    root = os.environ["CODEGREPROOT"]


def matching_files(term):
    key0 = term[:1]
    key1 = term[1:3]
    fs = set()
    for _dir, _, _ in os.walk(root):
        if _dir.endswith(".codegrep.index"):
            continue
        cgdir = os.path.join(_dir, ".codegrep.index")
        if not os.path.exists(cgdir):
            continue
        files = cPickle.load(open(cgdir + "/files"))
        try:
            inf = open(os.path.join(cgdir, str(ord(key0))))
        except IOError:
            continue
        d = cPickle.load(inf)
        if key1 not in d:
            continue

        p = subprocess.Popen(["xargs", "grep", "-l", term],
                             stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE)
        for i in d[key1]:
            p.stdin.write(os.path.join(_dir, files[i]) + "\n")
        p.stdin.close()
        for L in p.stdout.readlines():
            L = L.rstrip()
            if L not in fs:
                fs.add(L)
            yield L


if __name__ == "__main__":
    for f in matching_files(sys.argv[1]):
        print f
